services:
  - type: static
    name: survey-web-app
    buildCommand: node scripts/render-build.mjs
    staticPublishPath: out
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Will be set manually in dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY  
        sync: false  # Will be set manually in dashboard
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html