import { Question } from '@/types';

export const mockQuestions: { [surveyId: string]: Question[] } = {
  'survey-1': [
    {
      id: 'q1-1',
      survey_id: 'survey-1',
      question_text: 'What is your current employment status?',
      question_type: 'single_choice',
      required: true,
      order: 1,
      options: ['Full-time employee', 'Part-time employee', 'Contract worker', 'Retired'],
    },
    {
      id: 'q1-2',
      survey_id: 'survey-1',
      question_text: 'How satisfied are you with your current health insurance coverage?',
      question_type: 'scale',
      required: true,
      order: 2,
      options: ['1 - Very Dissatisfied', '2 - Dissatisfied', '3 - Neutral', '4 - Satisfied', '5 - Very Satisfied'],
    },
    {
      id: 'q1-3',
      survey_id: 'survey-1',
      question_text: 'Which healthcare services have you used in the past year? (Select all that apply)',
      question_type: 'multiple_choice',
      required: false,
      order: 3,
      options: ['Primary care physician', 'Specialist visits', 'Emergency room', 'Urgent care', 'Mental health services', 'Preventive care', 'Prescription medications', 'Dental care', 'Vision care'],
    },
    {
      id: 'q1-4',
      survey_id: 'survey-1',
      question_text: 'What is your approximate annual out-of-pocket healthcare spending?',
      question_type: 'number',
      required: true,
      order: 4,
    },
    {
      id: 'q1-5',
      survey_id: 'survey-1',
      question_text: 'Please describe any challenges you\'ve faced with your healthcare coverage',
      question_type: 'text',
      required: false,
      order: 5,
    },
    {
      id: 'q1-6',
      survey_id: 'survey-1',
      question_text: 'When did you last have a preventive health screening?',
      question_type: 'date',
      required: false,
      order: 6,
    },
    {
      id: 'q1-7',
      survey_id: 'survey-1',
      question_text: 'What is your preferred method for accessing healthcare?',
      question_type: 'single_choice',
      required: true,
      order: 7,
      options: ['In-person visits', 'Telehealth/Virtual visits', 'Combination of both'],
    },
    {
      id: 'q1-8',
      survey_id: 'survey-1',
      question_text: 'How many dependents are covered under your health plan?',
      question_type: 'number',
      required: true,
      order: 8,
    },
  ],
  'survey-2': [
    {
      id: 'q2-1',
      survey_id: 'survey-2',
      question_text: 'Which benefits are most important to you? (Rank top 3)',
      question_type: 'multiple_choice',
      required: true,
      order: 1,
      options: ['Health insurance', 'Dental insurance', 'Vision insurance', 'Retirement savings', 'Life insurance', 'Disability insurance', 'Flexible spending account', 'Paid time off'],
    },
    {
      id: 'q2-2',
      survey_id: 'survey-2',
      question_text: 'How well do you understand your current benefits package?',
      question_type: 'scale',
      required: true,
      order: 2,
      options: ['1 - Not at all', '2 - Slightly', '3 - Moderately', '4 - Well', '5 - Very well'],
    },
    {
      id: 'q2-3',
      survey_id: 'survey-2',
      question_text: 'What additional benefits would you like to see offered?',
      question_type: 'text',
      required: false,
      order: 3,
    },
  ],
  'survey-3': [
    {
      id: 'q3-1',
      survey_id: 'survey-3',
      question_text: 'Have you participated in any wellness programs this year?',
      question_type: 'single_choice',
      required: true,
      order: 1,
      options: ['Yes', 'No'],
    },
    {
      id: 'q3-2',
      survey_id: 'survey-3',
      question_text: 'Which wellness programs interest you most? (Select all that apply)',
      question_type: 'multiple_choice',
      required: false,
      order: 2,
      options: ['Fitness challenges', 'Nutrition counseling', 'Stress management', 'Smoking cessation', 'Mental health support', 'Health screenings'],
    },
  ],
};